//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn1_WPF.Model
{
    using DoAn1_WPF.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class DANHMUCHANG : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DANHMUCHANG()
        {
            this.HANGHOAs = new HashSet<HANGHOA>();
        }

        private string maLoaiHang;
        public string MaLoaiHang { get=>maLoaiHang; set { maLoaiHang = value;OnPropertyChanged(); } }

        private string tenLoaiHang;
        public string TenLoaiHang { get => tenLoaiHang; set { tenLoaiHang = value; OnPropertyChanged(); } }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HANGHOA> HANGHOAs { get; set; }
    }
}
