//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn1_WPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOAN
    {
        public int ID { get; set; }
        public string Ten { get; set; }
        public string TaiKhoan1 { get; set; }
        public string MatKhau { get; set; }
        public int IdQuyen { get; set; }
    
        public virtual PHANQUYEN PHANQUYEN { get; set; }
    }
}
