//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn1_WPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTPHIEUNHAP
    {
        public int ID { get; set; }
        public string MaPN { get; set; }
        public string MaNCC { get; set; }
        public string MaHang { get; set; }
        public string MaKho { get; set; }
        public Nullable<int> SLNhap { get; set; }
        public Nullable<double> DGNhap { get; set; }
    
        public virtual HANGHOA HANGHOA { get; set; }
        public virtual KHOHANG KHOHANG { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
        public virtual PHIEUNHAP PHIEUNHAP { get; set; }
    }
}
