//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn1_WPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTPHIEUXUAT
    {
        public int ID { get; set; }
        public string MaKH { get; set; }
        public string MaHang { get; set; }
        public string MaKho { get; set; }
        public Nullable<int> SLXuat { get; set; }
        public Nullable<double> DGXuat { get; set; }
        public string MaPX { get; set; }
    
        public virtual HANGHOA HANGHOA { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual KHOHANG KHOHANG { get; set; }
        public virtual PHIEUXUAT PHIEUXUAT { get; set; }
    }
}
